# Home Assistant Library Cache Entry
# Generated: 2025-10-12T00:00:00Z

library_info:
  name: "Home Assistant"
  context7_id: "/home-assistant/developers.home-assistant"
  trust_score: 10
  snippet_count: 1824
  last_updated: "2025-10-20T00:00:00Z"
  topics: 
    - "websocket-api"
    - "rest-api"
    - "authentication"
    - "events"
    - "states"
    - "services"
    - "entities"
    - "integration-development"
    - "automation-management"
    - "automation-deletion"
  
cache_entry:
  file_path: "libraries/homeassistant/docs.md"
  size_bytes: 22450
  hit_count: 1
  last_accessed: "2025-10-12T00:00:00Z"
  refresh_status: "current"
  next_refresh: "2025-11-19T00:00:00Z"
  
documentation_summary:
  topics_covered:
    - "WebSocket API connection and authentication"
    - "Event subscription and handling"
    - "Trigger-based subscriptions"
    - "REST API states management"
    - "REST API services execution"
    - "REST API automation deletion (VERIFIED Oct 2025)"
    - "Long-lived access tokens"
    - "Entity lifecycle and management"
    - "Event system and patterns"
    - "Integration development"
    - "Automation management and deletion"
    - "Security best practices"
    - "HA-Ingestor specific patterns"
  
  key_concepts:
    - "WebSocket authentication flow"
    - "State changed events structure"
    - "Event subscription patterns"
    - "REST API state vs service distinction"
    - "REST API automation deletion using attributes.id"
    - "Long-lived access token generation"
    - "Entity state structure with context"
    - "Service registration and execution"
    - "Custom WebSocket command registration"
    - "Event-driven architecture"
    - "Async integration patterns"
  
  code_examples:
    - "WebSocket connection and auth"
    - "Event subscription (all events, specific types)"
    - "Trigger subscription"
    - "Fire custom events"
    - "REST API state retrieval and updates"
    - "REST API automation deletion (verified)"
    - "Service calls with response data"
    - "Python service registration"
    - "WebSocket security with @require_admin"
    - "HA-Ingestor connection pattern"
    - "Event processing pattern"

quality_metrics:
  completeness: 95
  accuracy: 100
  relevance_to_project: 100
  code_example_coverage: 90
  
refresh_policy:
  type: "stable"
  max_age_days: 30
  auto_refresh: true
  stale_threshold_days: 45
  
project_usage:
  primary_service: "websocket-ingestion"
  related_services:
    - "admin-api"
    - "enrichment-pipeline"
  usage_patterns:
    - "Real-time event streaming"
    - "State change monitoring"
    - "Authentication with long-lived tokens"
    - "Event processing and normalization"
  
tags:
  - home-assistant
  - websocket
  - rest-api
  - real-time
  - events
  - states
  - authentication
  - integration
